### ISSUE TITLE
SVG icons are not displayed

### ISSUE THREAD

**Issue by etkinpinar** [FrederikBolding/chainlist#113]
Network icons that are SVG are not rendered due to `gatsby-plugin-sharp` / `gatsby-plugin-image` plugins [not ](https://github.com/gatsbyjs/gatsby/issues/10297#issuecomment-444419483) supporting SVGs. 

I suppose, publicURL of the nodes can be used to display them properly.

**Comment by FrederikBolding** [comment]
Thanks for reporting this! Will deploy a fix!
