### ISSUE TITLE
WT? server did something weird 

### ISSUE THREAD

**Issue by SQuIsHY7D3m** [FrederikBolding/chainlist#12]
When open window from windows on polygon main server I get that error message and unable to load anything from anywhere  even in opera.

**Comment by SQuIsHY7D3m** [comment]
![Screenshot_20220928-043349_MetaMask.jpg](https://user-images.githubusercontent.com/112392673/192747301-ca2d51e7-7abc-461c-b413-8c60eb15d0b8.jpg)

**Comment by FrederikBolding** [comment]
I'm not sure how this relates to Chainlist, if you are having problems with MetaMask please reach out to MetaMask support at http://support.metamask.io

**Comment by SQuIsHY7D3m** [comment]
It brought me here . Was a server to gihub issue. Brought me right this way. Still learning  thank you 😊
