### ISSUE TITLE
Significant Typing Delays

### ISSUE THREAD

**Issue by NobleOsinachi** [FrederikBolding/chainlist#52]
[Description]
I would like to raise an issue regarding a noticeable typing delay when using the search bar on the website. Currently, when I type a letter in the search bar for testnet networks, there is a significant lag before I can input the next character. This delay persists until the search has brought results for the previously inputted characters.

[Steps to Reproduce]
Open the website.
Navigate to the search bar for adding other networks to Metamask.
Begin typing in the search bar, entering individual characters one by one.
Observe the delay between each character input.

[Expected Behavior]
I expect the website to provide a smooth and responsive typing experience in the search bar. Ideally, there should be no noticeable delay between typing individual characters, regardless of the search results being fetched in the background.

[Actual Behavior]
Currently, when typing in the search bar, there is a significant delay of approximately 2 to 3 seconds before the next character can be entered. The delay persists until the search has brought results for the previously inputted characters. This makes the typing experience frustrating and time-consuming.

[Additional Information]
Operating System: [ Windows 10, Android 12]
Internet connection: [e.g., Wi-Fi]
This issue occurs consistently and can be reproduced on different machines and browsers.

[Impact]
The current typing delays significantly hamper the user experience, especially for users who rely heavily on the search functionality of the website. It makes the process of entering search queries cumbersome and discourages users from engaging with the site. By resolving this issue, the website's usability and user satisfaction can be greatly improved.

[Possible Solution]
Although I cannot diagnose the exact cause of the typing delays, some potential solutions could involve optimizing the search functionality to ensure a smoother and more responsive experience. Additionally, reviewing the website's front-end code and server-side processing may help identify any performance bottlenecks that contribute to the typing delays.

I appreciate your attention to this matter and look forward to a prompt resolution. Please let me know if any further information is required to address this issue effectively.

**Comment by FrederikBolding** [comment]
@NobleOsinachi This should be improved in the latest version, please try it out and let me know what you think!
